// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mojoPortal.Data.EFCore.Context;

#nullable disable

namespace mojoPortal.Data.EFCore.Migrations
{
    [DbContext(typeof(MojoPortalDbContext))]
    partial class MojoPortalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("mojoPortal.Data.EFCore.Entities.CommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<Guid>("ContentGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("ContentGuid");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedUtc");

                    b.Property<Guid>("FeatureGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("FeatureGuid");

                    b.Property<DateTime>("LastModUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModUtc");

                    b.Property<Guid?>("ModeratedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("ModeratedBy");

                    b.Property<string>("ModerationReason")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("ModerationReason");

                    b.Property<byte>("ModerationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("ModerationStatus");

                    b.Property<Guid>("ModuleGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("ModuleGuid");

                    b.Property<Guid>("ParentGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("ParentGuid");

                    b.Property<Guid>("SiteGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("SiteGuid");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.Property<string>("UserComment")
                        .HasColumnType("TEXT")
                        .HasColumnName("UserComment");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("UserEmail");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("UserGuid");

                    b.Property<string>("UserIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("UserIp");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("UserName");

                    b.Property<string>("UserUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("UserUrl");

                    b.HasKey("Id");

                    b.HasIndex("ContentGuid")
                        .HasDatabaseName("IX_mp_Comments_ContentGuid");

                    b.HasIndex("CreatedUtc")
                        .HasDatabaseName("IX_mp_Comments_CreatedUtc");

                    b.HasIndex("ParentGuid")
                        .HasDatabaseName("IX_mp_Comments_ParentGuid");

                    b.HasIndex("SiteGuid")
                        .HasDatabaseName("IX_mp_Comments_SiteGuid");

                    b.HasIndex("ParentGuid", "CreatedUtc")
                        .HasDatabaseName("IX_mp_Comments_Parent_Date");

                    b.HasIndex("ContentGuid", "ModerationStatus", "CreatedUtc")
                        .HasDatabaseName("IX_mp_Comments_Content_Status_Date");

                    b.ToTable("mp_Comments", (string)null);
                });

            modelBuilder.Entity("mojoPortal.Data.EFCore.Entities.CommentEntity", b =>
                {
                    b.HasOne("mojoPortal.Data.EFCore.Entities.CommentEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("mojoPortal.Data.EFCore.Entities.CommentEntity", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
